const ROLES=['IGL','RIFLE','SNIPER','SUPPORT','RIFLE'];
const DEFAULT={teams:Array.from({length:8},(_,i)=>({name:`${i<4?'IDP':'IME'} TEAM ${String.fromCharCode(65+i%4)}`,side:i<4?'idp':'ime',players:Array.from({length:5},(_,p)=>`${i<4?'IDP':'IME'} Player ${p+1}`)})),roles:Array.from({length:8},()=>[...ROLES]),scores:{},winners:{},live:{idp:'',ime:''},schedule:['15:00','16:30','18:00','19:30']};
const KEY='mapendos-v5'; const clone=o=>JSON.parse(JSON.stringify(o)); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function normalize(raw){const d=clone(DEFAULT),x=raw&&typeof raw==='object'?raw:d;return {teams:Array.from({length:8},(_,i)=>({name:x.teams?.[i]?.name??d.teams[i].name,side:i<4?'idp':'ime',players:Array.from({length:5},(_,p)=>x.teams?.[i]?.players?.[p]??d.teams[i].players[p])})),roles:Array.from({length:8},(_,i)=>Array.from({length:5},(_,p)=>x.roles?.[i]?.[p]??ROLES[p])),scores:x.scores||{},winners:x.winners||{},live:{...d.live,...(x.live||{})},schedule:Array.from({length:4},(_,i)=>x.schedule?.[i]??d.schedule[i])}}
let state;try{state=normalize(JSON.parse(localStorage.getItem(KEY)))}catch{state=clone(DEFAULT)}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const team=n=>state.teams[n]?.name||'TBD';
function winner(k,a,b){const w=state.winners[k];return w===a||w===b?w:'TBD'}
function matches(){const t=state.teams.map(x=>x.name||'TBD');return [
 ['q1','QUARTER FINAL 01',t[0],t[4]],['q2','QUARTER FINAL 02',t[1],t[5]],['q3','QUARTER FINAL 03',t[2],t[6]],['q4','QUARTER FINAL 04',t[3],t[7]],
 ['s1','SEMI FINAL 01',winner('q1',t[0],t[4]),winner('q2',t[1],t[5])],['s2','SEMI FINAL 02',winner('q3',t[2],t[6]),winner('q4',t[3],t[7])],
 ['gf','GRAND FINAL',winner('s1',winner('q1',t[0],t[4]),winner('q2',t[1],t[5])),winner('s2',winner('q3',t[2],t[6]),winner('q4',t[3],t[7]))],
 ['third','3RD PLACE',winner('s1',winner('q1',t[0],t[4]),winner('q2',t[1],t[5])),winner('s2',winner('q3',t[2],t[6]),winner('q4',t[3],t[7]))]
]}
function matchCard(m){const[k,label,a,b]=m,s=state.scores[k]||[];return `<div class="match-card"><small>${label}</small><div class="match-team ${state.winners[k]===a?'winner':''}"><span>${esc(a)}</span><b>${s[0]??''}</b></div><div class="match-team ${state.winners[k]===b?'winner':''}"><span>${esc(b)}</span><b>${s[1]??''}</b></div></div>`}
function renderBracket(){const ms=matches();ms.forEach(m=>{const el=document.querySelector(`[data-match="${m[0]}"]`);if(el)el.innerHTML=matchCard(m)});const gf=ms.find(m=>m[0]==='gf'),third=ms.find(m=>m[0]==='third');const c=winner('gf',gf[2],gf[3]);const runner=c==='TBD'?'TBD':(gf[2]===c?gf[3]:gf[2]);const p3=winner('third',third[2],third[3]);const p4=p3==='TBD'?'TBD':(third[2]===p3?third[3]:third[2]);document.querySelector('#standings').innerHTML=[['JUARA 1',c,'7.000.000'],['JUARA 2',runner,'4.000.000'],['JUARA 3',p3,'2.500.000'],['JUARA 4',p4,'1.500.000']].map(x=>`<div><span>${x[0]}</span><b>${esc(x[1])}</b><small>${x[2]}</small></div>`).join('')}
function renderRoster(){document.querySelector('#rosterGrid').innerHTML=state.teams.map((t,i)=>`<article class="roster-card ${t.side}"><div class="roster-head"><div class="mini-crest ${t.side}">${String.fromCharCode(65+i%4)}</div><div><span>MAPENDOS ${t.side.toUpperCase()} · TEAM ${String.fromCharCode(65+i%4)}</span><h3>${esc(t.name)}</h3></div></div><div class="players">${t.players.map((p,j)=>`<div><span class="num">0${j+1}</span><b>${esc(p)}</b><small>${esc(state.roles[i][j])}</small></div>`).join('')}</div></article>`).join('')}
function renderSchedule(){document.querySelector('#scheduleRows').innerHTML=state.schedule.map((time,i)=>`<div class="schedule-row"><span>0${i+1}</span><b>${esc(team(i))}</b><em>VS</em><b>${esc(team(i+4))}</b><time>${esc(time)}</time><strong>${i===0?'LIVE':'UPCOMING'}</strong></div>`).join('')}
function renderAdminTeams(){const el=document.querySelector('#adminTeams');if(!el)return;el.innerHTML=state.teams.map((t,i)=>`<article class="admin-team ${t.side}"><div class="admin-team-top"><b>MAPENDOS ${t.side.toUpperCase()} · TEAM ${String.fromCharCode(65+i%4)}</b><input data-team="${i}" value="${esc(t.name)}"></div>${t.players.map((p,j)=>`<div class="admin-player"><span>0${j+1}</span><input data-player="${i}:${j}" value="${esc(p)}"><select data-role="${i}:${j}">${ROLES.map(r=>`<option ${state.roles[i][j]===r?'selected':''}>${r}</option>`).join('')}</select></div>`).join('')}</article>`).join('')}
function renderResults(){const el=document.querySelector('#resultGrid');if(!el)return;el.innerHTML=matches().map(m=>{const[k,label,a,b]=m,s=state.scores[k]||[];return `<article class="result-card"><header><div><small>${label}</small><h4>${esc(a)} <i>VS</i> ${esc(b)}</h4></div><span>${state.winners[k]?'COMPLETED':'PENDING'}</span></header><div class="score-inputs"><label>${esc(a)}<input type="number" min="0" data-score="${k}:0" value="${s[0]??''}" ${a==='TBD'?'disabled':''}></label><strong>:</strong><label>${esc(b)}<input type="number" min="0" data-score="${k}:1" value="${s[1]??''}" ${b==='TBD'?'disabled':''}></label></div><div class="winner-buttons"><button data-win="${k}" data-team="${esc(a)}" ${a==='TBD'?'disabled':''}>${state.winners[k]===a?'✓ ':''}${esc(a)}</button><button data-win="${k}" data-team="${esc(b)}" ${b==='TBD'?'disabled':''}>${state.winners[k]===b?'✓ ':''}${esc(b)}</button></div></article>`}).join('')}
function renderStats(){const played=Object.keys(state.winners).filter(k=>k!=='fourth').length;const ms=matches(),gf=ms.find(m=>m[0]==='gf');document.querySelector('#adminStats').innerHTML=`<div><span>IDP TEAMS</span><b>04</b></div><div><span>IME TEAMS</span><b>04</b></div><div><span>MATCHES PLAYED</span><b>${played}<small>/ 8</small></b></div><div><span>CHAMPION</span><b>${esc(winner('gf',gf[2],gf[3]))}</b></div>`}
function bind(){document.querySelectorAll('[data-win]').forEach(b=>b.onclick=()=>{const k=b.dataset.win,t=b.dataset.team;state.winners[k]=state.winners[k]===t?'':t;invalidate(k);save();renderAll()});document.querySelectorAll('[data-score]').forEach(i=>i.onchange=()=>{const[k,n]=i.dataset.score.split(':');const v=i.value===''?'':Math.max(0,+i.value);state.scores[k]=state.scores[k]||['',''];state.scores[k][+n]=v;if(state.scores[k][0]!==''&&state.scores[k][1]!==''&&state.scores[k][0]!==state.scores[k][1]){const m=matches().find(x=>x[0]===k);state.winners[k]=state.scores[k][0]>state.scores[k][1]?m[2]:m[3];invalidate(k)}save();renderAll()});document.querySelectorAll('[data-team]').forEach(i=>i.oninput=()=>{state.teams[+i.dataset.team].name=i.value;save()});document.querySelectorAll('[data-player]').forEach(i=>i.oninput=()=>{const[a,b]=i.dataset.player.split(':');state.teams[+a].players[+b]=i.value;save()});document.querySelectorAll('[data-role]').forEach(i=>i.onchange=()=>{const[a,b]=i.dataset.role.split(':');state.roles[+a][+b]=i.value;save()})}
function invalidate(k){const deps={q1:['s1','gf','third'],q2:['s1','gf','third'],q3:['s2','gf','third'],q4:['s2','gf','third'],s1:['gf','third'],s2:['gf','third'],gf:[],third:[]};(deps[k]||[]).forEach(d=>{delete state.winners[d];delete state.scores[d]})}
function renderAll(){renderBracket();renderRoster();renderSchedule();renderAdminTeams();renderResults();renderStats();bind();const idp=document.querySelector('#admin-live-idp'),ime=document.querySelector('#admin-live-ime');if(idp)idp.value=state.live.idp;if(ime)ime.value=state.live.ime}
const nav=document.querySelector('#mainNav'),menu=document.querySelector('#menu');menu.onclick=()=>nav.classList.toggle('open');document.querySelectorAll('#mainNav a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');document.querySelectorAll('#mainNav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')});
const modal=document.querySelector('#admin');document.querySelector('#adminOpen').onclick=()=>modal.classList.add('show');document.querySelector('#adminClose').onclick=()=>modal.classList.remove('show');document.querySelectorAll('.admin-sidebar nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-sidebar nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-view').forEach(v=>v.classList.toggle('active',v.dataset.view===b.dataset.tab))});document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.querySelector(`.admin-sidebar nav button[data-tab="${b.dataset.jump}"]`).click());
document.querySelector('#clearResults').onclick=()=>{state.winners={};state.scores={};save();renderAll()};document.querySelector('#fillDemo').onclick=()=>{state=clone(DEFAULT);save();renderAll()};document.querySelector('#saveAdmin').onclick=()=>{save();document.querySelector('#adminSaveState').textContent='● ALL CHANGES SAVED'};document.querySelector('#saveLive').onclick=()=>{state.live.idp=document.querySelector('#admin-live-idp').value;state.live.ime=document.querySelector('#admin-live-ime').value;document.querySelectorAll('[data-schedule]').forEach(i=>state.schedule[+i.dataset.schedule]=i.value);save();document.querySelector('#adminSaveState').textContent='● LIVE SETTINGS SAVED'};document.querySelector('#exportData').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='mapendos-backup.json';a.click()};document.querySelector('#importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=normalize(JSON.parse(r.result));save();renderAll()}catch{alert('JSON tidak valid')}};r.readAsText(f)};document.querySelector('#resetAdmin').onclick=()=>{if(confirm('Reset semua data?')){state=clone(DEFAULT);save();renderAll()}};
renderAll();
