const DEFAULT={teams:Array.from({length:8},(_,i)=>({name:`${i<4?'IDP':'IME'} TEAM ${String.fromCharCode(65+i%4)}`,side:i<4?'idp':'ime',players:Array.from({length:5},(_,p)=>`${i<4?'IDP':'IME'} Player ${p+1}`)})),scores:{},winners:{},live:{idp:'',ime:''}};
const KEY='mapendos-v7-pages';
const clone=o=>JSON.parse(JSON.stringify(o));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function normalize(raw){const d=clone(DEFAULT),x=raw&&typeof raw==='object'?raw:d;return {teams:Array.from({length:8},(_,i)=>({name:x.teams?.[i]?.name??d.teams[i].name,side:i<4?'idp':'ime',players:Array.from({length:5},(_,p)=>x.teams?.[i]?.players?.[p]??d.teams[i].players[p])})),scores:x.scores||{},winners:x.winners||{},live:{...d.live,...(x.live||{})}}}
let state;try{state=normalize(JSON.parse(localStorage.getItem(KEY)))}catch{state=clone(DEFAULT)}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const winner=(k,a,b)=>{const w=state.winners[k];return w===a||w===b?w:'TBD'};
const loser=(k,a,b)=>{const w=state.winners[k];return !w?'TBD':w===a?b:a};
function matches(){const t=state.teams.map(x=>x.name||'TBD');const q=[['q1','QUARTER FINAL 01',t[0],t[1]],['q2','QUARTER FINAL 02',t[2],t[3]],['q3','QUARTER FINAL 03',t[4],t[5]],['q4','QUARTER FINAL 04',t[6],t[7]]];const s=[['s1','SEMI FINAL 01',winner('q1',t[0],t[1]),winner('q2',t[2],t[3])],['s2','SEMI FINAL 02',winner('q3',t[4],t[5]),winner('q4',t[6],t[7])]];const gf=['gf','GRAND FINAL',winner('s1',s[0][2],s[0][3]),winner('s2',s[1][2],s[1][3])];const third=['third','3RD PLACE',loser('s1',s[0][2],s[0][3]),loser('s2',s[1][2],s[1][3])];return [...q,...s,gf,third]}
function refCard(m){const[k,label,a,b]=m,s=state.scores[k]||[];const side=x=>state.teams.find(t=>t.name===x)?.side||'';return `<div class="match-card-ref"><div class="team-row ${side(a)} ${a==='TBD'?'tbd':''} ${state.winners[k]===a?'winner':''}"><span>${esc(a)}</span><b>${s[0]??''}</b></div><div class="team-row ${side(b)} ${b==='TBD'?'tbd':''} ${state.winners[k]===b?'winner':''}"><span>${esc(b)}</span><b>${s[1]??''}</b></div></div>`}
function renderBracket(){const ms=matches();document.querySelectorAll('[data-match]').forEach(el=>{const m=ms.find(x=>x[0]===el.dataset.match);if(m)el.innerHTML=refCard(m)});const gf=ms.find(m=>m[0]==='gf'),third=ms.find(m=>m[0]==='third');if(!gf)return;const c=winner('gf',gf[2],gf[3]);const runner=loser('gf',gf[2],gf[3]);const p3=winner('third',third[2],third[3]);const p4=loser('third',third[2],third[3]);const champ=document.querySelector('#championName');if(champ)champ.textContent=c;const standings=document.querySelector('#standings');if(standings)standings.innerHTML=[['JUARA 1',c,'7.000.000'],['JUARA 2',runner,'4.000.000'],['JUARA 3',p3,'2.500.000'],['JUARA 4',p4,'1.500.000']].map(x=>`<div><span>${x[0]}</span><b>${esc(x[1])}</b><small>${x[2]}</small></div>`).join('')}
function renderRoster(){const el=document.querySelector('#rosterGrid');if(!el)return;el.innerHTML=state.teams.map((t,i)=>`<article class="roster-card ${t.side}"><div class="roster-head"><div class="mini-crest ${t.side}">${String.fromCharCode(65+i%4)}</div><div><span>MAPENDOS ${t.side.toUpperCase()} · TEAM ${String.fromCharCode(65+i%4)}</span><h3>${esc(t.name)}</h3></div></div><div class="players">${t.players.map((p,j)=>`<div><span class="num">0${j+1}</span><b>${esc(p)}</b></div>`).join('')}</div></article>`).join('')}
function renderAdminTeams(){const el=document.querySelector('#adminTeams');if(!el)return;el.innerHTML=state.teams.map((t,i)=>`<article class="admin-team ${t.side}"><div class="admin-team-top"><b>TEAM ${String.fromCharCode(65+i%4)} · ${t.side.toUpperCase()}</b><input data-team="${i}" value="${esc(t.name)}"></div>${t.players.map((p,j)=>`<div class="admin-player"><span>0${j+1}</span><input data-player="${i}:${j}" value="${esc(p)}"></div>`).join('')}</article>`).join('');bindAdminTeamInputs()}
function renderResults(){const el=document.querySelector('#resultGrid');if(!el)return;el.innerHTML=matches().map(m=>{const[k,label,a,b]=m,s=state.scores[k]||[];return `<article class="result-card"><header><div><small>${label}</small><h4>${esc(a)} <i>VS</i> ${esc(b)}</h4></div><span>${state.winners[k]?'COMPLETED':'PENDING'}</span></header><div class="score-inputs"><label>${esc(a)}<input type="number" min="0" data-score="${k}:0" value="${s[0]??''}" ${a==='TBD'?'disabled':''}></label><strong>:</strong><label>${esc(b)}<input type="number" min="0" data-score="${k}:1" value="${s[1]??''}" ${b==='TBD'?'disabled':''}></label></div><div class="winner-buttons"><button data-win="${k}" data-team="${esc(a)}" ${a==='TBD'?'disabled':''}>${state.winners[k]===a?'✓ ':''}${esc(a)}</button><button data-win="${k}" data-team="${esc(b)}" ${b==='TBD'?'disabled':''}>${state.winners[k]===b?'✓ ':''}${esc(b)}</button></div></article>`}).join('');bindResults()}
function renderStats(){const el=document.querySelector('#adminStats');if(!el)return;const played=Object.keys(state.winners).length,ms=matches(),gf=ms.find(m=>m[0]==='gf');el.innerHTML=`<div><span>IDP TEAMS</span><b>04</b></div><div><span>IME TEAMS</span><b>04</b></div><div><span>MATCHES PLAYED</span><b>${played}<small>/ 8</small></b></div><div><span>CHAMPION</span><b>${esc(winner('gf',gf[2],gf[3]))}</b></div>`}
function invalidate(k){const deps={q1:['s1','gf','third'],q2:['s1','gf','third'],q3:['s2','gf','third'],q4:['s2','gf','third'],s1:['gf','third'],s2:['gf','third'],gf:[],third:[]};(deps[k]||[]).forEach(d=>{delete state.winners[d];delete state.scores[d]})}
function bindResults(){document.querySelectorAll('[data-win]').forEach(b=>b.onclick=()=>{const k=b.dataset.win,t=b.dataset.team;if(t==='TBD')return;state.winners[k]=state.winners[k]===t?'':t;invalidate(k);save();renderAll()});document.querySelectorAll('[data-score]').forEach(i=>i.onchange=()=>{const[k,n]=i.dataset.score.split(':');const v=i.value===''?'':Math.max(0,+i.value);state.scores[k]=state.scores[k]||['',''];state.scores[k][+n]=v;if(state.scores[k][0]!==''&&state.scores[k][1]!==''&&state.scores[k][0]!==state.scores[k][1]){const m=matches().find(x=>x[0]===k);state.winners[k]=state.scores[k][0]>state.scores[k][1]?m[2]:m[3];invalidate(k)}save();renderAll()})}
function bindAdminTeamInputs(){document.querySelectorAll('[data-team]').forEach(i=>i.oninput=()=>{state.teams[+i.dataset.team].name=i.value;save()});document.querySelectorAll('[data-player]').forEach(i=>i.oninput=()=>{const[a,b]=i.dataset.player.split(':');state.teams[+a].players[+b]=i.value;save()})}
function renderLive(){const idp=document.querySelector('#idpThumb'),ime=document.querySelector('#imeThumb');if(idp)idp.onclick=()=>state.live.idp&&window.open(state.live.idp,'_blank');if(ime)ime.onclick=()=>state.live.ime&&window.open(state.live.ime,'_blank');const a=document.querySelector('#admin-live-idp'),b=document.querySelector('#admin-live-ime');if(a)a.value=state.live.idp;if(b)b.value=state.live.ime}
function renderAll(){renderBracket();renderRoster();renderAdminTeams();renderResults();renderStats();renderLive()}
function setupNav(){const nav=document.querySelector('#mainNav'),menu=document.querySelector('#menu');if(menu&&nav)menu.onclick=()=>nav.classList.toggle('open');document.querySelectorAll('#mainNav a').forEach(a=>a.onclick=()=>nav?.classList.remove('open'))}
function setupAdmin(){const modal=document.querySelector('#admin');const open=document.querySelector('#adminOpen');if(open&&modal)open.onclick=()=>modal.classList.add('show');const close=document.querySelector('#adminClose');if(close&&modal)close.onclick=()=>modal.classList.remove('show');document.querySelectorAll('.admin-sidebar nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-sidebar nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-view').forEach(v=>v.classList.toggle('active',v.dataset.view===b.dataset.tab))});document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.querySelector(`.admin-sidebar nav button[data-tab="${b.dataset.jump}"]`)?.click());const clear=document.querySelector('#clearResults');if(clear)clear.onclick=()=>{state.winners={};state.scores={};save();renderAll()};const demo=document.querySelector('#fillDemo');if(demo)demo.onclick=()=>{state=clone(DEFAULT);save();renderAll()};const saveAdmin=document.querySelector('#saveAdmin');if(saveAdmin)saveAdmin.onclick=()=>save();const saveLive=document.querySelector('#saveLive');if(saveLive)saveLive.onclick=()=>{state.live.idp=document.querySelector('#admin-live-idp')?.value||'';state.live.ime=document.querySelector('#admin-live-ime')?.value||'';save();renderLive()};const exp=document.querySelector('#exportData');if(exp)exp.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='mapendos-backup.json';a.click()};const imp=document.querySelector('#importData');if(imp)imp.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=normalize(JSON.parse(r.result));save();renderAll()}catch{alert('JSON tidak valid')}};r.readAsText(f)};const reset=document.querySelector('#resetAdmin');if(reset)reset.onclick=()=>{if(confirm('Reset semua data?')){state=clone(DEFAULT);save();renderAll()}}}
setupNav();setupAdmin();renderAll();
